import DocumentViewer, { DocumentSection, DocumentType } from '@/components/DocumentViewer';
import type { Meta, StoryObj } from '@storybook/nextjs-vite';
import { useState } from 'react';

const meta: Meta<typeof DocumentViewer> = {
  title: 'Components/DocumentViewer',
  component: DocumentViewer,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component:
          'Component for viewing documents with 3 fixed predefined sections: Medical order, Authorization and Informed consent. Each section can be in pending, uploading or completed state.',
      },
    },
  },
  argTypes: {
    title: {
      control: 'text',
      description: 'Document viewer title',
    },
    sections: {
      control: 'object',
      description: 'List of the 3 fixed document sections',
    },
    currentDocumentUrl: {
      control: 'text',
      description: 'URL of current document to show in the viewer',
    },
    isLoading: {
      control: 'boolean',
      description: 'Current document loading state',
    },
    onUpload: {
      action: 'upload',
      description: 'Function executed to upload a new PDF file to a specific section',
    },
    onSelectSection: {
      action: 'select',
      description: 'Function executed when clicking on a section to select it',
    },
    onViewSection: {
      action: 'view',
      description: 'Function executed when clicking the View document button',
    },
    onDeleteSection: {
      action: 'delete',
      description: 'Function executed when clicking the Delete document button',
    },
    onSectionUpdated: {
      action: 'sectionUpdated',
      description: 'Function executed when a section is updated',
    },
    onCurrentDocumentChange: {
      action: 'currentDocumentChange',
      description: 'Function executed when the current document in the viewer is updated',
    },
    className: {
      control: 'text',
      description: 'Additional CSS class',
    },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

const createDocumentPreview = (title: string, content: string) => {
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 40px;
      background: #ffffff;
      margin: 0;
      line-height: 1.6;
      color: #333;
    }
    .document-header {
      text-align: center;
      border-bottom: 3px solid #007bff;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .document-title {
      font-size: 24px;
      font-weight: bold;
      color: #007bff;
      margin: 0;
    }
    .document-subtitle {
      font-size: 16px;
      color: #666;
      margin: 10px 0 0 0;
    }
    .document-content {
      font-size: 14px;
      margin: 20px 0;
      padding: 20px;
      background: #f8f9fa;
      border-radius: 8px;
      border-left: 4px solid #007bff;
    }
    .document-footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #dee2e6;
      font-size: 12px;
      color: #6c757d;
      text-align: center;
    }
    .stamp {
      display: inline-block;
      padding: 10px 20px;
      border: 2px solid #28a745;
      color: #28a745;
      font-weight: bold;
      transform: rotate(-5deg);
      margin: 20px 0;
    }
  </style>
</head>
<body>
  <div class="document-header">
    <h1 class="document-title">${title}</h1>
    <p class="document-subtitle">INTEGRITY System - Medical Documents</p>
  </div>
  
  <div class="document-content">
    <p><strong>Description:</strong> ${content}</p>
    <p><strong>Generation date:</strong> ${new Date().toLocaleDateString('en-US')}</p>
    <p><strong>Status:</strong> <span class="stamp">COMPLETED</span></p>
    <p><strong>Notes:</strong> This is an example document generated for DocumentViewer component demonstration in Storybook.</p>
  </div>
  
  <div class="document-content">
    <h3>System Information</h3>
    <p>This document has been automatically generated by the INTEGRITY system for demonstration purposes.</p>
    <p>In a real environment, this would show the actual content of the corresponding medical document.</p>
  </div>
  
  <div class="document-footer">
    <p>© 2024 INTEGRITY System - Medical Document Management</p>
    <p>This is an example document generated for Storybook</p>
  </div>
</body>
</html>`;

  return `data:text/html;charset=utf-8,${encodeURIComponent(htmlContent)}`;
};

const DOCUMENT_URLS = {
  'orden-medica': createDocumentPreview(
    'MEDICAL ORDER',
    'Medical order document for outpatient procedure. Includes specific indications for the treatment to follow.',
  ),
  autorizacion: createDocumentPreview(
    'INSURANCE AUTHORIZATION',
    'Authorization document issued by the insurance for the requested medical treatment.',
  ),
  'consentimiento-informado': createDocumentPreview(
    'INFORMED CONSENT',
    'Document where the patient grants their informed consent for the medical procedure to be performed.',
  ),
};

const createInitialSections = (): DocumentSection[] => [
  {
    id: 'orden-medica',
    name: 'Medical order',
    status: 'completed',
    url: DOCUMENT_URLS['orden-medica'],
    selected: true,
  },
  {
    id: 'autorizacion',
    name: 'Authorization',
    status: 'pending',
  },
  {
    id: 'consentimiento-informado',
    name: 'Informed consent',
    status: 'pending',
  },
];

export const Default: Story = {
  args: {
    title: 'Appointment documents',
    sections: [
      {
        id: 'orden-medica',
        name: 'Medical order',
        status: 'completed',
        url: DOCUMENT_URLS['orden-medica'],
        selected: true,
      },
      {
        id: 'autorizacion',
        name: 'Authorization',
        status: 'pending',
      },
      {
        id: 'consentimiento-informado',
        name: 'Informed consent',
        status: 'pending',
      },
    ],
    currentDocumentUrl: DOCUMENT_URLS['orden-medica'],
    isLoading: false,
  },
  parameters: {
    docs: {
      description: {
        story:
          'Basic version of the component controlled by Storybook controls. Allows modifying all props from the controls panel to see how they affect the component.',
      },
    },
  },
};

export const Interactive: Story = {
  render: () => {
    const [sections, setSections] = useState<DocumentSection[]>(createInitialSections());
    const [currentDocumentUrl, setCurrentDocumentUrl] = useState<string>(DOCUMENT_URLS['orden-medica']);
    const [isLoading, setIsLoading] = useState(false);

    const handleUpload = async (file: File, sectionId: DocumentType): Promise<DocumentSection> => {
      console.log(`📄 Uploading file: ${file.name} to section: ${sectionId}`);

      const sectionToUpdate = sections.find((s) => s.id === sectionId);
      if (!sectionToUpdate) throw new Error('Section not found');

      const uploadingSection: DocumentSection = {
        ...sectionToUpdate,
        status: 'uploading',
      };

      setSections((prev) => prev.map((section) => (section.id === sectionId ? uploadingSection : section)));

      await new Promise((resolve) => setTimeout(resolve, 2000));

      const completedSection: DocumentSection = {
        ...uploadingSection,
        status: 'completed',
        url: DOCUMENT_URLS[sectionId],
      };

      setSections((prev) => prev.map((section) => (section.id === sectionId ? completedSection : section)));

      return completedSection;
    };

    const handleSelectSection = (selectedSection: DocumentSection) => {
      if (selectedSection.status === 'uploading') return;

      console.log(`🔄 Selecting section: ${selectedSection.name}`);

      const updatedSections = sections.map((section) => ({
        ...section,
        selected: section.id === selectedSection.id,
      }));

      setSections(updatedSections);

      if (selectedSection.url) {
        setCurrentDocumentUrl(selectedSection.url);
        setIsLoading(true);
        setTimeout(() => setIsLoading(false), 1000);
      } else {
        setCurrentDocumentUrl('');
      }
    };

    const handleDeleteSection = (sectionToDelete: DocumentSection) => {
      console.log(`🗑️ Deleting document from: ${sectionToDelete.name}`);

      const resetSection: DocumentSection = {
        ...sectionToDelete,
        status: 'pending',
        url: undefined,
      };

      setSections((prev) => prev.map((section) => (section.id === sectionToDelete.id ? resetSection : section)));

      if (sectionToDelete.selected) {
        setCurrentDocumentUrl('');
      }
    };

    return (
      <DocumentViewer
        title="Appointment documents"
        sections={sections}
        currentDocumentUrl={currentDocumentUrl}
        isLoading={isLoading}
        onUpload={handleUpload}
        onSelectSection={handleSelectSection}
        onViewSection={(section) => alert(`View: ${section.name}`)}
        onDeleteSection={handleDeleteSection}
        onSectionUpdated={(section) => console.log(`📄 Section updated: ${section.name}`)}
        onCurrentDocumentChange={(url) => {
          console.log('📄 Updating current document:', url);
          setCurrentDocumentUrl(url);
        }}
      />
    );
  },
  parameters: {
    docs: {
      description: {
        story:
          'Fully interactive component that demonstrates all functionalities: PDF file upload, loading states, selection, deletion and document replacement. The 3 sections are fixed: Medical order, Authorization and Informed consent. Key features: selection blocking during upload, conditionally enabled buttons based on document status, improved visual feedback with loading spinners, and informative tooltips.',
      },
    },
  },
};
